import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "bn" | "en";

const translations = {
  // Sidebar
  dashboard: { bn: "ড্যাশবোর্ড", en: "Dashboard" },
  purchase: { bn: "ক্রয়", en: "Purchase" },
  factories: { bn: "কারখানা", en: "Factories" },
  transfers: { bn: "ট্রান্সফার", en: "Transfers" },
  production: { bn: "উৎপাদন", en: "Production" },
  inventory: { bn: "ইনভেন্টরি", en: "Inventory" },
  sales: { bn: "বিক্রয় ও বায়ার", en: "Sales & Buyers" },
  party: { bn: "পার্টি ও কমিশন", en: "Party & Commission" },
  cash: { bn: "ক্যাশ ম্যানেজমেন্ট", en: "Cash Management" },
  challan: { bn: "চালান ও ইনভয়েস", en: "Challan & Invoice" },
  analytics: { bn: "বিশ্লেষণ", en: "Analytics" },
  settings: { bn: "সেটিংস", en: "Settings" },

  // Common
  search: { bn: "অনুসন্ধান...", en: "Search..." },
  hairProcessingErp: { bn: "হেয়ার প্রসেসিং ইআরপি", en: "Hair Processing ERP" },
  totalRawStock: { bn: "মোট কাঁচামাল স্টক", en: "Total Raw Stock" },
  acrossAllFactories: { bn: "সকল কারখানা মিলিয়ে", en: "Across all factories" },
  activeFactories: { bn: "সক্রিয় কারখানা", en: "Active Factories" },
  todaysCashBalance: { bn: "আজকের ক্যাশ ব্যালেন্স", en: "Today's Cash Balance" },
  afterAllTransactions: { bn: "সকল লেনদেন পরে", en: "After all transactions" },
  pendingDues: { bn: "বকেয়া পাওনা", en: "Pending Dues" },
  productionFlow: { bn: "উৎপাদন প্রবাহ", en: "Production Flow" },
  multiStageProcessing: { bn: "মাল্টি-স্টেজ প্রসেসিং পাইপলাইন", en: "Multi-stage processing pipeline" },
  gradeWiseInventory: { bn: "গ্রেড অনুযায়ী ইনভেন্টরি", en: "Grade-wise Inventory" },
  stockByHairLength: { bn: "চুলের দৈর্ঘ্য অনুযায়ী স্টক", en: "Stock by hair length (all factories)" },
  todaysCashFlow: { bn: "আজকের ক্যাশ ফ্লো", en: "Today's Cash Flow" },
  opening: { bn: "প্রারম্ভিক", en: "Opening" },
  cashIn: { bn: "ক্যাশ ইন", en: "Cash In" },
  cashOut: { bn: "ক্যাশ আউট", en: "Cash Out" },
  closing: { bn: "সমাপনী", en: "Closing" },
  recentTransactions: { bn: "সাম্প্রতিক লেনদেন", en: "Recent Transactions" },
  latestActivity: { bn: "সকল কার্যক্রমের সর্বশেষ তথ্য", en: "Latest activity across all operations" },
  factoryOverview: { bn: "কারখানার সারসংক্ষেপ", en: "Factory Overview" },
  allLocations: { bn: "সকল লোকেশন", en: "All locations" },
  activeBatches: { bn: "সক্রিয় ব্যাচ", en: "Active Batches" },
  avgEfficiency: { bn: "গড় দক্ষতা", en: "Avg Efficiency" },
  activeBuyers: { bn: "সক্রিয় বায়ার", en: "Active Buyers" },
  pendingTransfers: { bn: "মুলতুবি ট্রান্সফার", en: "Pending Transfers" },
  efficiency: { bn: "দক্ষতা", en: "Efficiency" },
  id: { bn: "আইডি", en: "ID" },
  type: { bn: "ধরন", en: "Type" },
  description: { bn: "বিবরণ", en: "Description" },
  amount: { bn: "পরিমাণ", en: "Amount" },
  status: { bn: "স্ট্যাটাস", en: "Status" },
  total: { bn: "মোট", en: "Total" },
  loss: { bn: "ক্ষতি", en: "loss" },
  raw: { bn: "গুটি (কাঁচা)", en: "Guti (Raw)" },
  processed: { bn: "কাছি (প্রসেসড)", en: "Kachi (Processed)" },
  final: { bn: "টু বাই টু (ফাইনাল)", en: "Two by Two (Final)" },

  // Purchase module
  purchaseModule: { bn: "ক্রয় মডিউল", en: "Purchase Module" },
  addNewPurchase: { bn: "নতুন ক্রয় যোগ করুন", en: "Add New Purchase" },
  supplierName: { bn: "সরবরাহকারীর নাম", en: "Supplier Name" },
  country: { bn: "দেশ", en: "Country" },
  bangladesh: { bn: "বাংলাদেশ", en: "Bangladesh" },
  india: { bn: "ভারত", en: "India" },
  currency: { bn: "মুদ্রা", en: "Currency" },
  weight: { bn: "ওজন (KG)", en: "Weight (KG)" },
  pricePerKg: { bn: "প্রতি কেজি মূল্য", en: "Price per KG" },
  totalPrice: { bn: "মোট মূল্য", en: "Total Price" },
  exchangeRate: { bn: "বিনিময় হার", en: "Exchange Rate" },
  middleman: { bn: "মধ্যস্থকারী", en: "Middleman" },
  middlemanName: { bn: "মধ্যস্থকারীর নাম", en: "Middleman Name" },
  save: { bn: "সংরক্ষণ", en: "Save" },
  cancel: { bn: "বাতিল", en: "Cancel" },
  date: { bn: "তারিখ", en: "Date" },
  supplier: { bn: "সরবরাহকারী", en: "Supplier" },
  action: { bn: "কার্যক্রম", en: "Action" },
  paid: { bn: "পরিশোধিত", en: "Paid" },
  unpaid: { bn: "অপরিশোধিত", en: "Unpaid" },
  partial: { bn: "আংশিক", en: "Partial" },
  purchaseHistory: { bn: "ক্রয়ের ইতিহাস", en: "Purchase History" },
  multiCurrencySupport: { bn: "মাল্টি-কারেন্সি সাপোর্ট (BDT/INR)", en: "Multi-currency support (BDT/INR)" },

  // Production module
  productionModule: { bn: "উৎপাদন মডিউল", en: "Production Module" },
  createBatch: { bn: "নতুন ব্যাচ তৈরি", en: "Create Batch" },
  batchId: { bn: "ব্যাচ আইডি", en: "Batch ID" },
  stage: { bn: "স্টেজ", en: "Stage" },
  inputWeight: { bn: "ইনপুট ওজন", en: "Input Weight" },
  outputWeight: { bn: "আউটপুট ওজন", en: "Output Weight" },
  lossWeight: { bn: "ক্ষতি ওজন", en: "Loss Weight" },
  factory: { bn: "কারখানা", en: "Factory" },
  batchTracking: { bn: "ব্যাচ ট্র্যাকিং", en: "Batch Tracking" },
  stageWiseProcessing: { bn: "স্টেজ অনুযায়ী প্রসেসিং", en: "Stage-wise processing" },
  moveToNextStage: { bn: "পরবর্তী স্টেজে পাঠান", en: "Move to Next Stage" },
  complete: { bn: "সম্পন্ন", en: "Complete" },
  inProgress: { bn: "চলমান", en: "In Progress" },

  // Inventory module
  inventoryModule: { bn: "ইনভেন্টরি মডিউল", en: "Inventory Module" },
  grade: { bn: "গ্রেড", en: "Grade" },
  stock: { bn: "স্টক", en: "Stock" },
  rate: { bn: "রেট", en: "Rate" },
  value: { bn: "মূল্য", en: "Value" },
  lowStock: { bn: "কম স্টক", en: "Low Stock" },
  factoryWiseStock: { bn: "কারখানা অনুযায়ী স্টক", en: "Factory-wise Stock" },
  totalValuation: { bn: "মোট মূল্যায়ন", en: "Total Valuation" },

  // Sales module
  salesModule: { bn: "বিক্রয় ও বায়ার মডিউল", en: "Sales & Buyer Module" },
  addSale: { bn: "নতুন বিক্রয়", en: "Add Sale" },
  buyerName: { bn: "বায়ারের নাম", en: "Buyer Name" },
  buyerType: { bn: "বায়ারের ধরন", en: "Buyer Type" },
  chinese: { bn: "চাইনিজ", en: "Chinese" },
  local: { bn: "স্থানীয়", en: "Local" },
  china: { bn: "চীন", en: "China" },
  otherCountry: { bn: "অন্যান্য দেশ", en: "Other Country" },
  buyerCountry: { bn: "বায়ারের দেশ", en: "Buyer Country" },
  gutiGrade: { bn: "গুটির গ্রেড/ধরন", en: "Guti Grade/Type" },
  productType: { bn: "পণ্যের ধরন", en: "Product Type" },
  kachiProduct: { bn: "কাছি", en: "Kachi" },
  twobytwoProduct: { bn: "টু বাই টু", en: "Two by Two" },
  gutiProduct: { bn: "গুটি", en: "Guti" },
  twobytwoStock: { bn: "টু বাই টু স্টক", en: "Two by Two Stock" },
  gutiStock: { bn: "গুটি স্টক", en: "Guti Stock" },
  gutiStockModule: { bn: "গুটি চুল স্টক ম্যানেজমেন্ট", en: "Guti Hair Stock Management" },
  gutiStockDesc: { bn: "গুটি চুলের স্টক এন্ট্রি ও ট্র্যাকিং", en: "Guti hair stock entries & tracking" },
  twobytwoModule: { bn: "টু বাই টু স্টক ম্যানেজমেন্ট", en: "Two by Two Stock Management" },
  ownerName: { bn: "মালিকের নাম", en: "Owner Name" },
  chhat: { bn: "ছাট", en: "Chhat (Waste)" },
  remand: { bn: "রিমান্ড", en: "Remand" },
  totalInput: { bn: "মোট ইনপুট", en: "Total Input" },
  totalOutput: { bn: "মোট আউটপুট", en: "Total Output" },
  gradeWiseBreakdown: { bn: "গ্রেড অনুযায়ী বিবরণ", en: "Grade-wise Breakdown" },
  gradeWiseRate: { bn: "গ্রেড অনুযায়ী রেট", en: "Grade-wise Rate" },
  dueAmount: { bn: "বকেয়া পরিমাণ", en: "Due Amount" },
  salesHistory: { bn: "বিক্রয়ের ইতিহাস", en: "Sales History" },
  buyer: { bn: "বায়ার", en: "Buyer" },
  advance: { bn: "অগ্রিম", en: "Advance" },
  due: { bn: "বকেয়া", en: "Due" },

  // Party module
  partyModule: { bn: "পার্টি ও কমিশন মডিউল", en: "Party & Commission Module" },
  partyName: { bn: "পার্টির নাম", en: "Party Name" },
  buyerRate: { bn: "বায়ার রেট", en: "Buyer Rate" },
  partyRate: { bn: "পার্টি রেট", en: "Party Rate" },
  margin: { bn: "মার্জিন", en: "Margin" },
  commission: { bn: "কমিশন", en: "Commission" },
  settlement: { bn: "নিষ্পত্তি", en: "Settlement" },
  totalSales: { bn: "মোট বিক্রয়", en: "Total Sales" },
  processingCost: { bn: "প্রসেসিং খরচ", en: "Processing Cost" },
  payable: { bn: "প্রদেয়", en: "Payable" },
  hiddenBuyerRate: { bn: "বায়ার রেট (গোপন)", en: "Buyer Rate (Hidden)" },
  partySettlement: { bn: "পার্টি নিষ্পত্তি", en: "Party Settlement" },

  // Cash module
  cashModule: { bn: "ক্যাশ ম্যানেজমেন্ট মডিউল", en: "Cash Management Module" },
  addEntry: { bn: "নতুন এন্ট্রি", en: "Add Entry" },
  category: { bn: "ক্যাটাগরি", en: "Category" },
  laborWages: { bn: "শ্রমিক বেতন", en: "Labor Wages" },
  food: { bn: "খাবার", en: "Food" },
  transport: { bn: "পরিবহন", en: "Transport" },
  office: { bn: "অফিস", en: "Office" },
  other: { bn: "অন্যান্য", en: "Other" },
  monthlySummary: { bn: "মাসিক সারসংক্ষেপ", en: "Monthly Summary" },
  dailyCashbook: { bn: "দৈনিক ক্যাশবুক", en: "Daily Cashbook" },

  // Transfer module
  transferModule: { bn: "ট্রান্সফার মডিউল", en: "Transfer Module" },
  from: { bn: "থেকে", en: "From" },
  to: { bn: "গন্তব্য", en: "To" },
  transferWeight: { bn: "ট্রান্সফার ওজন", en: "Transfer Weight" },
  receivedWeight: { bn: "প্রাপ্ত ওজন", en: "Received Weight" },
  weightDiff: { bn: "ওজন পার্থক্য", en: "Weight Difference" },
  transferHistory: { bn: "ট্রান্সফার ইতিহাস", en: "Transfer History" },
  newTransfer: { bn: "নতুন ট্রান্সফার", en: "New Transfer" },
  inTransit: { bn: "ট্রানজিটে", en: "In Transit" },
  received: { bn: "প্রাপ্ত", en: "Received" },

  // Challan module
  challanModule: { bn: "চালান ও ইনভয়েস মডিউল", en: "Challan & Invoice Module" },
  createChallan: { bn: "নতুন চালান", en: "Create Challan" },
  challanNo: { bn: "চালান নং", en: "Challan No" },
  gradeDetails: { bn: "গ্রেড বিবরণ", en: "Grade Details" },
  printPdf: { bn: "PDF প্রিন্ট", en: "Print PDF" },
  challanHistory: { bn: "চালান ইতিহাস", en: "Challan History" },

  // Analytics module
  analyticsModule: { bn: "বিশ্লেষণ ড্যাশবোর্ড", en: "Analytics Dashboard" },
  ownProductionProfit: { bn: "নিজস্ব উৎপাদন লাভ", en: "Own Production Profit" },
  partyProfit: { bn: "পার্টি লাভ", en: "Party Profit" },
  commissionIncome: { bn: "কমিশন আয়", en: "Commission Income" },
  factoryEfficiency: { bn: "কারখানা দক্ষতা", en: "Factory Efficiency" },
  lossAnalysis: { bn: "ক্ষতি বিশ্লেষণ", en: "Loss Analysis" },
  currencyImpact: { bn: "মুদ্রা প্রভাব বিশ্লেষণ", en: "Currency Impact Analysis" },
  profitTrend: { bn: "লাভের প্রবণতা", en: "Profit Trend" },

  // Settings
  settingsModule: { bn: "সেটিংস", en: "Settings" },
  language: { bn: "ভাষা", en: "Language" },
  bangla: { bn: "বাংলা", en: "Bangla" },
  english: { bn: "ইংরেজি", en: "English" },
  companyName: { bn: "কোম্পানির নাম", en: "Company Name" },
  userManagement: { bn: "ইউজার ম্যানেজমেন্ট", en: "User Management" },
  generalSettings: { bn: "সাধারণ সেটিংস", en: "General Settings" },

  // Factory module
  factoryModule: { bn: "কারখানা মডিউল", en: "Factory Module" },
  addFactory: { bn: "নতুন কারখানা", en: "Add Factory" },
  factoryName: { bn: "কারখানার নাম", en: "Factory Name" },
  location: { bn: "অবস্থান", en: "Location" },
  factoryType: { bn: "কারখানার ধরন", en: "Factory Type" },
  headOffice: { bn: "প্রধান কার্যালয়", en: "Head Office" },
  branch: { bn: "শাখা", en: "Branch" },
  active: { bn: "সক্রিয়", en: "Active" },
  inactive: { bn: "নিষ্ক্রিয়", en: "Inactive" },

  // Auth
  login: { bn: "লগইন", en: "Login" },
  signup: { bn: "রেজিস্ট্রেশন", en: "Sign Up" },
  email: { bn: "ইমেইল", en: "Email" },
  password: { bn: "পাসওয়ার্ড", en: "Password" },
  fullName: { bn: "পুরো নাম", en: "Full Name" },
  loginSuccess: { bn: "সফলভাবে লগইন হয়েছে", en: "Logged in successfully" },
  signupSuccess: { bn: "রেজিস্ট্রেশন সফল", en: "Registration successful" },
  checkEmail: { bn: "ইমেইল ভেরিফাই করুন", en: "Please check your email to verify" },
  error: { bn: "ত্রুটি", en: "Error" },
  noAccount: { bn: "অ্যাকাউন্ট নেই? রেজিস্ট্রেশন করুন", en: "Don't have an account? Sign up" },
  hasAccount: { bn: "অ্যাকাউন্ট আছে? লগইন করুন", en: "Already have an account? Login" },
  logout: { bn: "লগআউট", en: "Logout" },
  role: { bn: "ভূমিকা", en: "Role" },
  admin: { bn: "অ্যাডমিন", en: "Admin" },
  factoryManager: { bn: "ফ্যাক্টরি ম্যানেজার", en: "Factory Manager" },
  accountant: { bn: "হিসাবরক্ষক", en: "Accountant" },

  // New - CRUD & Settings
  edit: { bn: "সম্পাদনা", en: "Edit" },
  delete: { bn: "মুছুন", en: "Delete" },
  loading: { bn: "লোড হচ্ছে...", en: "Loading..." },
  noData: { bn: "কোন তথ্য নেই", en: "No data found" },
  saved: { bn: "সংরক্ষিত হয়েছে", en: "Saved successfully" },
  deleted: { bn: "মুছে ফেলা হয়েছে", en: "Deleted successfully" },
  confirmDelete: { bn: "মুছে ফেলতে চান?", en: "Confirm delete?" },
  manageRoles: { bn: "ভূমিকা পরিবর্তন করুন", en: "Manage Roles" },
  users: { bn: "ব্যবহারকারী", en: "Users" },
  roleUpdated: { bn: "ভূমিকা আপডেট হয়েছে", en: "Role updated" },
  selectRole: { bn: "ভূমিকা নির্বাচন করুন", en: "Select Role" },
  paymentStatus: { bn: "পেমেন্ট স্ট্যাটাস", en: "Payment Status" },
  batchCode: { bn: "ব্যাচ কোড", en: "Batch Code" },
  addSettlement: { bn: "নতুন সেটেলমেন্ট", en: "Add Settlement" },
  update: { bn: "আপডেট", en: "Update" },
  personName: { bn: "ব্যক্তির নাম", en: "Person Name" },
  paymentMethod: { bn: "পেমেন্ট মাধ্যম", en: "Payment Method" },
  bankTransfer: { bn: "ব্যাংক ট্রান্সফার", en: "Bank Transfer" },
  nagadCash: { bn: "নগদ ক্যাশ", en: "Cash" },
  bataRate: { bn: "বাটা (পয়সা)", en: "Bata (Paisa)" },
  bdtPaid: { bn: "বাংলা টাকায় পরিশোধ", en: "BDT Paid" },
  recipientName: { bn: "প্রাপকের নাম", en: "Recipient Name" },
  recipientAddress: { bn: "প্রাপকের ঠিকানা", en: "Recipient Address" },
  recipientPhone: { bn: "প্রাপকের ফোন", en: "Recipient Phone" },
  courierName: { bn: "কুরিয়ার সার্ভিস", en: "Courier Service" },
  bookingSlip: { bn: "বুকিং স্লিপ", en: "Booking Slip" },
  printBookingSlip: { bn: "বুকিং স্লিপ প্রিন্ট", en: "Print Booking Slip" },
  senderInfo: { bn: "প্রেরকের তথ্য", en: "Sender Info" },
  receiverInfo: { bn: "প্রাপকের তথ্য", en: "Receiver Info" },
  productDetails: { bn: "পণ্যের বিবরণ", en: "Product Details" },
  bookingSlipModule: { bn: "বুকিং স্লিপ মডিউল", en: "Booking Slip Module" },
  bookingSlipDesc: { bn: "কুরিয়ারে পাঠানোর বুকিং স্লিপ তৈরি করুন", en: "Create booking slips for courier dispatch" },
  newBookingSlip: { bn: "নতুন বুকিং স্লিপ", en: "New Booking Slip" },
  bookingSlipHistory: { bn: "বুকিং স্লিপ ইতিহাস", en: "Booking Slip History" },
  booking: { bn: "বুকিং স্লিপ", en: "Booking Slip" },
  companyLogo: { bn: "কোম্পানির লোগো", en: "Company Logo" },
  uploadLogo: { bn: "লোগো আপলোড করুন", en: "Upload Logo" },
  logoUploaded: { bn: "লোগো আপলোড হয়েছে", en: "Logo uploaded successfully" },
  companyInfo: { bn: "কোম্পানির তথ্য", en: "Company Information" },
  companyAddress: { bn: "কোম্পানির ঠিকানা", en: "Company Address" },
  phone: { bn: "ফোন", en: "Phone" },
  tagline: { bn: "ট্যাগলাইন", en: "Tagline" },
  userAccessDesc: { bn: "প্রতিটি ইউজারের রোল ও মডিউল অ্যাক্সেস দেখুন এবং পরিবর্তন করুন", en: "View and change each user's role and module access" },
  ledger: { bn: "পাওনা ও দেনা", en: "Receivable & Payable" },
  ledgerModule: { bn: "পাওনা ও দেনা হিসাব", en: "Receivable & Payable Ledger" },
  ledgerDesc: { bn: "কার কাছে কত পাবো, কাকে কত দিতে হবে", en: "Track who owes you and who you owe" },
  totalReceivable: { bn: "মোট পাওনা (আমরা পাবো)", en: "Total Receivable" },
  totalPayable: { bn: "মোট দেনা (আমরা দেবো)", en: "Total Payable" },
  netBalance: { bn: "নীট ব্যালেন্স", en: "Net Balance" },
  weWillGet: { bn: "আমরা পাবো (বায়ারদের বকেয়া)", en: "We Will Receive (Buyer Dues)" },
  weWillPay: { bn: "আমাদের দিতে হবে (সরবরাহকারী/পার্টি)", en: "We Will Pay (Supplier/Party)" },
  persons: { bn: "জন", en: "persons" },
  forgotPassword: { bn: "পাসওয়ার্ড ভুলে গেছেন?", en: "Forgot password?" },
  resetPassword: { bn: "পাসওয়ার্ড রিসেট করুন", en: "Reset Password" },
  resetPasswordSent: { bn: "পাসওয়ার্ড রিসেট লিংক ইমেইলে পাঠানো হয়েছে", en: "Password reset link sent to your email" },
  backToLogin: { bn: "লগইন পেজে ফিরে যান", en: "Back to Login" },
  enterEmailForReset: { bn: "রিসেট লিংক পেতে আপনার ইমেইল দিন", en: "Enter your email to receive a reset link" },
  contactAdminForAccess: { bn: "অ্যাক্সেস পেতে এডমিনের সাথে যোগাযোগ করুন", en: "Contact admin for access" },
  createAccount: { bn: "অ্যাকাউন্ট তৈরি করুন", en: "Create Account" },
  signupSuccessDesc: { bn: "এখন লগইন করুন অথবা ইমেইল কনফার্ম করুন", en: "Now log in or confirm your email" },
  addUser: { bn: "নতুন ইউজার যোগ করুন", en: "Add New User" },
  createUser: { bn: "ইউজার তৈরি করুন", en: "Create User" },
  userCreated: { bn: "ইউজার সফলভাবে তৈরি হয়েছে", en: "User created successfully" },
  userCreateFailed: { bn: "ইউজার তৈরি করা যায়নি", en: "Failed to create user" },
  allTransactions: { bn: "সকল লেনদেন", en: "All Transactions" },
  transactionHistory: { bn: "লেনদেনের ইতিহাস", en: "Transaction History" },
  fromDate: { bn: "শুরুর তারিখ", en: "From Date" },
  toDate: { bn: "শেষের তারিখ", en: "To Date" },
  print: { bn: "প্রিন্ট", en: "Print" },
  downloadPdf: { bn: "PDF ডাউনলোড", en: "Download PDF" },
  filterByDate: { bn: "তারিখ অনুযায়ী ফিল্টার", en: "Filter by Date" },
  today: { bn: "আজ", en: "Today" },
  thisWeek: { bn: "এই সপ্তাহ", en: "This Week" },
  thisMonth: { bn: "এই মাস", en: "This Month" },
  thisYear: { bn: "এই বছর", en: "This Year" },
  allTime: { bn: "সবসময়", en: "All Time" },
  customRange: { bn: "কাস্টম রেঞ্জ", en: "Custom Range" },
  selectedItems: { bn: "নির্বাচিত আইটেম", en: "Selected Items" },
  selectAll: { bn: "সব নির্বাচন", en: "Select All" },
  printSelected: { bn: "নির্বাচিত প্রিন্ট", en: "Print Selected" },
  noTransactions: { bn: "কোন লেনদেন পাওয়া যায়নি", en: "No transactions found" },
  companyPad: { bn: "কোম্পানি প্যাড", en: "Company Pad" },
  profitLoss: { bn: "লাভ-ক্ষতি রিপোর্ট", en: "Profit & Loss" },
  dailyReport: { bn: "দৈনিক রিপোর্ট", en: "Daily Report" },
  buyerDues: { bn: "বায়ার বকেয়া", en: "Buyer Dues" },
  suppliers: { bn: "সরবরাহকারী", en: "Suppliers" },
  auditLog: { bn: "অডিট লগ", en: "Audit Log" },
  buyerProfiles: { bn: "বায়ার প্রোফাইল", en: "Buyer Profiles" },
} as const;

type TranslationKey = keyof typeof translations;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("bn");

  const t = (key: TranslationKey): string => {
    return translations[key]?.[lang] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
